// packages/vue-app/src/screens/List/index.vue
<template>
  <div>
    <Loader v-if="loading" />
    <vue-headful v-if="!loading" title="Pokédex" />
    <row :gutter="12" v-if="!loading">
      <column v-for="pokemon in pokemons" :key="pokemon.id" :xs="12" :sm="6" :lg="4">
        <CardPokemon :pokemon="pokemon" />
      </column>
    </row>
  </div>
</template>

<script>
import Loader from "../../components/Loader";
import CardPokemon from "../../containers/CardPokemon";
import { allPokemons } from "../../services/pokemons";

export default {
  name: "List",
  data() {
    return {
      pokemons: [],
      loading: true
    };
  },
  async mounted() {
    const data = await allPokemons(0);
    this.pokemons = [...this.pokemons, ...data.results];

    setTimeout(() => (this.loading = false), 2000);
  },
  components: {
    Loader,
    CardPokemon
  }
};
</script>

// packages/svelte-app/src/screens/List/index.svelte
<script>
  import { onMount } from "svelte";
  import SvelteInfiniteScroll from "svelte-infinite-scroll";
  import Grid from "svelte-grid-responsive";
  import DocumentTitle from "svelte-document-title";

  import CardPokemon from "../../containers/CardPokemon/index.svelte";
  import Loader from "../../components/Loader/index.svelte";

  import { allPokemons } from "../../services/pokemons";

  let pokemons = [];
  let hasMore = false;
  let page = -1;
  let loading = true;

  onMount(() => {
    getData();
  });

  const getData = async () => {
    page++;

    const data = await allPokemons(page);
    pokemons = [...pokemons, ...data.results];
    hasMore = !!data.next;

    setTimeout(() => (loading = false), 2000);
  };
</script>

{#if loading}
  <Loader />
{:else}
  <DocumentTitle title="Pokédex">
    <Grid container gutter={12}>
      {#each pokemons as pokemon}
        <Grid xs={12} sm={6} lg={4}>
          <CardPokemon {pokemon} />
        </Grid>
      {/each}
    </Grid>
  </DocumentTitle>
{/if}

<SvelteInfiniteScroll
  {hasMore}
  threshold={200}
  window
  on:loadMore={() => getData()} />
