// packages/react-app/src/screens/List/index.js
import React, { useEffect, useState } from "react";
import InfiniteScroll from "react-infinite-scroller";
import { Row, Col } from "react-grid-system";

import CardPokemon from "../../containers/CardPokemon";

import { allPokemons } from "../../services/pokemons";
import Loader from "../../components/Loader";

const ListScreen = () => {
  const [loading, setLoading] = useState(true);
  const [pokemons, setPokemons] = useState([]);
  const [hasMore, setHasMore] = useState(false);

  useEffect(() => {
    const getData = async () => {
      const data = await allPokemons(0);

      setPokemons(pokemons => [...pokemons, ...data.results]);
      setHasMore(!!data.next);
      setTimeout(() => setLoading(false), 1000);
    };

    getData();
  }, []);

  const getMore = async page => {
    const data = await allPokemons(page);

    setPokemons([...pokemons, ...data.results]);
    setHasMore(!!data.next);
  };

  if (loading) {
    return <Loader />;
  }

  return (
    <InfiniteScroll pageStart={0} loadMore={getMore} hasMore={hasMore}>
      <Row gutterWidth={12}>
        {pokemons.map(item => (
          <Col key={item.id} xs={12} sm={6} lg={4} style={{ marginBottom: 12 }}>
            <CardPokemon pokemon={item} />
          </Col>
        ))}
      </Row>
    </InfiniteScroll>
  );
};

export default ListScreen;

// packages/svelte-app/src/screens/List/index.svelte
<script>
  import { onMount } from "svelte";
  import SvelteInfiniteScroll from "svelte-infinite-scroll";
  import Grid from "svelte-grid-responsive";

  import CardPokemon from "../../containers/CardPokemon/index.svelte";
  import Loader from "../../components/Loader/index.svelte";

  import { allPokemons } from "../../services/pokemons";

  let pokemons = [];
  let hasMore = false;
  let page = -1;
  let loading = true;

  onMount(() => {
    getData();
  });

  const getData = async () => {
    page++;

    const data = await allPokemons(page);
    pokemons = [...pokemons, ...data.results];
    hasMore = !!data.next;

    setTimeout(() => (loading = false), 2000);
  };
</script>

{#if loading}
  <Loader />
{:else}
  <Grid container gutter={12}>
    {#each pokemons as pokemon}
      <Grid xs={12} sm={6} lg={4}>
        <CardPokemon {pokemon} />
      </Grid>
    {/each}
  </Grid>
{/if}

<SvelteInfiniteScroll
  {hasMore}
  threshold={200}
  window
  on:loadMore={() => getData()} />
