// packages/svelte-app/src/components/Loader/index.svelte
<script>
  import DocumentTitle from "svelte-document-title";
</script>

<style>
  .root-loader {
    display: flex;
    width: 100%;
    height: 100%;
    position: fixed;
    top: 64px;
    left: 0;
    align-items: center;
    justify-content: center;
  }
</style>

<DocumentTitle title="loading...">
  <div role="alert" aria-busy="true" class="root-loader">
    <img alt="Loader" src="assets/spinner.gif" />
  </div>
</DocumentTitle>

// packages/react-app/src/components/Loader/index.js
import React from "react";
import DocumentTitle from "react-document-title";

import style from "./Loader.module.css";

const LoaderComponent = () => (
  <DocumentTitle title="loading...">
    <div role="alert" aria-busy="true" className={style.root}>
      <img alt="Loader" src="assets/spinner.gif" />
    </div>
  </DocumentTitle>
);

export default LoaderComponent;
