// packages/react-app/src/components/Progress/index.js
import React from "react";
import style from "./Progress.module.css";

const ProgressComponent = ({ label, value }) => (
  <div className={style.root}>
    <label for={label}>{label}</label>
    <progress className={style.progress} id={label} value={value} max="100" />
  </div>
);

export default ProgressComponent;

// packages/svelte-app/src/components/Progress/index.svelte
<script>
  export let label;
  export let value;
</script>

<style>
  .root {
    width: 100%;
    display: flex;
    flex-direction: column;
    margin-bottom: 10px;
  }

  progress {
    width: 100%;
  }
</style>

<div class="root">
  <label for={label}>{label}</label>
  <progress id={label} {value} max="100" />
</div>
