// packages/svelte-app/src/components/Loader/index.svelte
<script>
  import DocumentTitle from "svelte-document-title";
</script>

<style>
  .root-loader {
    display: flex;
    width: 100%;
    height: 100%;
    position: fixed;
    top: 64px;
    left: 0;
    align-items: center;
    justify-content: center;
  }
</style>

<DocumentTitle title="loading...">
  <div role="alert" aria-busy="true" class="root-loader">
    <img alt="Loader" src="assets/spinner.gif" />
  </div>
</DocumentTitle>

// packages/vue-app/src/components/Loader/index.vue
<template>
  <div role="alert" aria-busy="true" class="root">
    <vue-headful title="loading..." />
    <img alt="Loader" src="assets/spinner.gif" />
  </div>
</template>

<script>
export default {
  name: "Loader"
};
</script>

<style scoped>
.root {
  display: flex;
  width: 100%;
  height: 100%;
  position: fixed;
  top: 64px;
  left: 0;
  align-items: center;
  justify-content: center;
}
</style>
