// packages/react-app/src/core/App.js
import React from "react";
import { BrowserRouter, Switch, Route } from "react-router-dom";

import Header from "../components/Header";
import Content from "../components/Content";

import ListScreen from "../screens/List";
import PokemonScreen from "../screens/Pokemon";

const App = () => {
  return (
    <>
      <Header />
      <BrowserRouter basename="/react/">
        <Content>
          <Switch>
            <Route exact path="/" component={ListScreen} />
            <Route exact path="/pokemon/:id" component={PokemonScreen} />
          </Switch>
        </Content>
      </BrowserRouter>
    </>
  );
};

export default App;

// packages/svelte-app/src/App.svelte
<script>
  import { Router, Link, Route } from "svelte-routing";

  import Header from "./components/Header/index.svelte";
  import Content from "./components/Content/index.svelte";

  import ListScreen from "./screens/List/index.svelte";
  import PokemonScreen from "./screens/Pokemon/index.svelte";
</script>

<style>

</style>

<main>
  <Router basepath="/svelte/">
    <Header />
    <Content>
      <Route path="/" component={ListScreen} />
      <Route path="/pokemon/:id" component={PokemonScreen} />
    </Content>
  </Router>
</main>
